description: 'CNN'
output_dir: '/home/raknop/research/decat/nn_output/'

data:
    name: supernova
    data_dir: '/home/raknop/research/decat/nn_input/'
    prefix: 'majority_jpg_20211104'

model:
    name: cnn
    input_shape: [51, 51, 3]
    n_classes: 2

optimizer:
        #name: Adam
        lr: 0.0005 ## Not used in code

training:
    batch_size: 128
    n_epochs: 50
    lr_warmup_epochs: 0
    loss: binary_crossentropy
    metrics: [accuracy]
