description: 'CNN'

data_dir: '/global/project/projectdirs/dasrepo/vpa/supernova_cnn/data/gathered_data/'
#data_dir: '/data0/vpa/atlas_cnn/data/RPVSusyData/'
output_dir: '/global/project/projectdirs/dasrepo/vpa/supernova_cnn/data/results_data/results/'

data:
    name: supernova

model:
    name: cnn
    input_shape: [51, 51, 1]
    n_classes: 2
    #dropout: 0.5

optimizer:
#     name: Adam
#    lr: 0.001

training:
    batch_size: 64 
    n_epochs: 100
    lr_warmup_epochs: 0
    loss: binary_crossentropy
    metrics: [accuracy]
